### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by haipinglu**
### Description
Update readme to align with the video to release. The video will be uploaded over this weekend.

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Review by bobturneruk — APPROVED** [review]
Looks good! I guess the plan is to merge only once the video goes up?

**Comment by haipinglu** [comment]
> Looks good! I guess the plan is to merge only once the video goes up?

Yes, the video will be online over the weekend. Then I will update the link and merge. You've asked for an Intro earlier so I hope that would be helpful to you as well.

**Comment by bobturneruk** [comment]
Looking forward to it. I will comment on the slides soon.

**Review by RaivoKoot — APPROVED** [review]
Nice. I like this. I think the intro paragraph is now very clear and obvious 👍

**Pull request merged**
