### PR TITLE
only ci test multiple python versions on linux

### LINKED ISSUE #96: Reduce test matrix
Test all versions on Linux, only latest on Windows + Mac.

- 
- 
- 
-

### PR DESCRIPTION
**Pull request by bobturneruk**
Fixes #96 

### Description
Removes tests on platform-python version combinations that do not justify the time and complexity.

### Status
**Ready**

### Types of changes
- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] In-line docstrings updated.
- [ ] [Source for documentation at `docs`](https://github.com/pykale/pykale/tree/master/docs/source) manually updated for new API.

### CODE REVIEW

**Comment by bobturneruk** [comment]
Will require some GitHub settings to change reflecting fewer test cases being run.

**Review by haipinglu — APPROVED** [review]

**Review by pz-white — APPROVED** [review]

**Comment by bobturneruk** [comment]
I can't change the settings as I dropped by admin privileges for testing purposes a while back. @haipinglu if you make me admin I'll get this to merge.

**Comment by haipinglu** [comment]
> I can't change the settings as I dropped by admin privileges for testing purposes a while back. @haipinglu if you make me admin I'll get this to merge.

I've already updated the required tests. You do not need admin to merge. I turned on auto merge after review and approval. It cannot be merged due to the cancelled test. I could remove the auto-merge if you want to try merging.

**Comment by haipinglu** [comment]
See whether rerunning can pass.

**Comment by haipinglu** [comment]
@bobturneruk Ready for you to merge. Let me know if any problem.

**Pull request merged**
