### PR TITLE
Reduce tests for video, fix video load, & remove binder icon

### LINKED ISSUE #175: [Bug] test_video_access error for python 3.7/3.8 starting 2nd July
# 🐛 Bug

CI `test_video_access` started to report errors since yesterday PM for python 3.7 and 3.8. It was OK when Bob ran it yesterday morning and for other recent tests. Not sure what has been changed in between on the system or elsewhere. The tests can pass on python 3.6. The error is `TypeError` and seems to be associated with `pickle.load` below

```
tests/loaddata/test_video_access.py:101: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
kale/loaddata/video_access.py:254: in get_train
    n_classes=self._n_classes,
kale/loaddata/video_datasets.py:120: in __init__
    test_mode,
kale/loaddata/videos.py:149: in __init__
    self._parse_list()
kale/loaddata/video_datasets.py:124: in _parse_list
    self.video_list = [VideoRecord(x, self.img_path) for x in list(self.make_dataset())]
kale/loaddata/video_datasets.py:146: in make_dataset
    input_file = pickle.load(input_file)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TypeError: __cinit__() takes at least 2 positional arguments (0 given)

pandas/_libs/internals.pyx:572: TypeError
```

Some related searches
https://github.com/h5py/h5py/issues/1092
https://stackoverflow.com/questions/34569664/typeerror-cinit-takes-exactly-8-positional-arguments-3-given-when-loa
https://bugs.python.org/issue32696

## To reproduce

See https://github.com/pykale/pykale/runs/2978244183 or https://github.com/pykale/pykale/runs/2975724777 or rerun past successful tests

** Stack trace/error message **
```
=================================== FAILURES ===================================
_ test_get_source_target[class_subset0-max-natural-0.1-EPIC;8;epic_D1_train.pkl;epic_D1_test.pkl-EPIC;8;epic_D1_train.pkl;epic_D1_test.pkl] _

source_cfg = 'EPIC;8;epic_D1_train.pkl;epic_D1_test.pkl'
target_cfg = 'EPIC;8;epic_D1_train.pkl;epic_D1_test.pkl', val_ratio = 0.1
weight_type = 'natural', datasize_type = 'max'
testing_cfg = CfgNode({'DATASET': CfgNode({'ROOT': '/home/runner/work/tests/test_data/video_test_data/', 'IMAGE_MODALITY': 'joint', ...R_TRAINLIST': 'epic_D1_train.pkl', 'TAR_TESTLIST': 'epic_D1_test.pkl', 'WEIGHT_TYPE': 'natural', 'SIZE_TYPE': 'max'})})
class_subset = [1, 3, 8]

    @pytest.mark.parametrize("source_cfg", SOURCES)
    @pytest.mark.parametrize("target_cfg", TARGETS)
    @pytest.mark.parametrize("val_ratio", VAL_RATIO)
    @pytest.mark.parametrize("weight_type", WEIGHT_TYPE)
    @pytest.mark.parametrize("datasize_type", DATASIZE_TYPE)
    @pytest.mark.parametrize("class_subset", CLASS_SUBSETS)
    def test_get_source_target(source_cfg, target_cfg, val_ratio, weight_type, datasize_type, testing_cfg, class_subset):
        source_name, source_n_class, source_trainlist, source_testlist = source_cfg.split(";")
        target_name, target_n_class, target_trainlist, target_testlist = target_cfg.split(";")
        n_class = eval(min(source_n_class, target_n_class))
    
        # get cfg parameters
        cfg = testing_cfg
        cfg.DATASET.SOURCE = source_name
        cfg.DATASET.SRC_TRAINLIST = source_trainlist
        cfg.DATASET.SRC_TESTLIST = source_testlist
        cfg.DATASET.TARGET = target_name
        cfg.DATASET.TAR_TRAINLIST = target_trainlist
        cfg.DATASET.TAR_TESTLIST = target_testlist
        cfg.DATASET.WEIGHT_TYPE = weight_type
        cfg.DATASET.SIZE_TYPE = datasize_type
    
        download_file_by_url(
            url=url,
            output_directory=str(Path(cfg.DATASET.ROOT).parent.absolute()),
            output_file_name="video_test_data.zip",
            file_format="zip",
        )
    
        # test get_source_target
        source, target, num_classes = VideoDataset.get_source_target(
            VideoDataset(source_name), VideoDataset(target_name), seed, cfg
        )
    
        assert num_classes == n_class
        assert isinstance(source, dict)
        assert isinstance(target, dict)
        assert isinstance(source["rgb"], VideoDatasetAccess)
        assert isinstance(target["rgb"], VideoDatasetAccess)
        assert isinstance(source["flow"], VideoDatasetAccess)
        assert isinstance(target["flow"], VideoDatasetAccess)
    
        # test get_train & get_test
>       assert isinstance(source["rgb"].get_train(), torch.utils.data.Dataset)

tests/loaddata/test_video_access.py:101: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
kale/loaddata/video_access.py:254: in get_train
    n_classes=self._n_classes,
kale/loaddata/video_datasets.py:120: in __init__
    test_mode,
kale/loaddata/videos.py:149: in __init__
    self._parse_list()
kale/loaddata/video_datasets.py:124: in _parse_list
    self.video_list = [VideoRecord(x, self.img_path) for x in list(self.make_dataset())]
kale/loaddata/video_datasets.py:146: in make_dataset
    input_file = pickle.load(input_file)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   TypeError: __cinit__() takes at least 2 positional arguments (0 given)

pandas/_libs/internals.pyx:572: TypeError
----------------------------- Captured stdout call -----------------------------
Downloading https://github.com/pykale/data/raw/main/video_data/video_test_data.zip to /home/runner/work/tests/test_data/video_test_data.zip
Extracting /home/runner/work/tests/test_data/video_test_data.zip to /home/runner/work/tests/test_data
----------------------------- Captured stderr call -----------------------------
```

## Expected Behaviour

I've rerun 10+ times in the past 18 hours but all failed

## Environment

See GitHub actions

### PR DESCRIPTION
**Pull request by XianyuanLiu**
Fixes #175.

### Description
- Reduce tests for video 
- Fix video load
- Remove binder icon

### Status
**Ready**

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [ ] New tests added to cover the changes.
- [ ] In-line docstrings updated.
- [ ] [Source for documentation at `docs`](https://github.com/pykale/pykale/tree/main/docs/source) manually updated for new API.

### CODE REVIEW

**Comment by haipinglu** [comment]
@bobturneruk Forcing pandas>=1.3.0 is not working for 3.6
https://github.com/pykale/pykale/runs/2993309532
`ERROR: Could not find a version that satisfies the requirement pandas>=1.3.0`

@XianyuanLiu  You did not seem to have fixed pandas 1.3.0 compatibility problem yet.

**Comment by XianyuanLiu** [comment]
Yes, I haven't solved it yet because it seems a general problem. I report it to pandas. 
Dataframes saved with pandas<1.3.0 and "pickle" is no longer loadable with pandas 1.3.0 in https://github.com/pandas-dev/pandas/issues/42345.

**Comment by haipinglu** [comment]
> Yes, I haven't solved it yet because it seems a general problem. I report it to pandas.
> Dataframes saved with pandas<1.3.0 and "pickle" is no longer loadable with pandas 1.3.0 in [pandas-dev/pandas#42345](https://github.com/pandas-dev/pandas/issues/42345).
> 
> Btw, Pandas added this problem to the 1.3.1 milestone which due time is July 25.

Good finding! `test_video_feature_extractor` has several hundreds (?) tests, 60+% of all tests. Can they be reduced as well?

**Comment by mustafa1728** [comment]
I tried using the pandas function `pd.read_pickle()` instead of `pickle.load()`, and the tests pass on my local. 
~~~python
# with open(self.annotationfile_path, "rb") as input_file:
#     input_file = pickle.load(input_file)
 input_file = pd.read_pickle(self.annotationfile_path)
~~~
May I test on GitHub by committing in this PR?

I am not sure about the reason for this difference, but I think `pd.read_pickle()` should work for older versions of pandas as well.

**Comment by haipinglu** [comment]
> May I test on GitHub by committing in this PR?

Yes, please go ahead.

**Comment by XianyuanLiu** [comment]
Yes, we can use `pd.read_pickle`. I have tested `pickle.load` and `pd.read_pickle` by the code below.
```
with open(path, "rb") as input_file:
    input_file1 = pickle.load(input_file)
with open(path, "rb") as input_file:
    input_file2 = pd.read_pickle(input_file)
print(pd.testing.assert_frame_equal(input_file1, input_file2))
```
Output is `None`, which means no difference between `input_file1` and `input_file2`.

Like what @mustafa1728 said, `pandas` uses `pickle.load` inside `pd.read_pickle` but updated this function this time. But still don't know the reason.

**Comment by XianyuanLiu** [comment]
@mustafa1728 Do we need this `with ... open ...` here to avoid forgetting to close the file? I am not sure if it is needed.

 https://stackoverflow.com/questions/20101021/how-to-close-the-file-after-pickle-load-in-python

**Comment by mustafa1728** [comment]
> Do we need this `with ... open ...` here to avoid forgetting to close the file? I am not sure if it is needed.

The read_pickle() function has a `with ... open ...` block inside it [here](https://github.com/pandas-dev/pandas/blob/f00ed8f47020034e752baf0250483053340971b0/pandas/io/pickle.py#L196), so its not needed, as it is closing the file anyways. Also, this works both ways (path or file handler as in the [docs](https://github.com/pandas-dev/pandas/blob/f00ed8f47020034e752baf0250483053340971b0/pandas/io/pickle.py#L139)), so it should not cause any errors inside the `with ... open` block either.

**Comment by XianyuanLiu** [comment]
Oh, my mistake. I regarded it as `pickle.load`, but not the new one.

**Review by haipinglu — APPROVED** [review]

**Pull request merged**
