### PR TITLE
Create test_sampler.py and update doc for tests

### LINKED ISSUE #185: Adapt tests from Pytorch-ada
Pytorch-ada has some testing examples which can help us improve. (sampler, dataset_access and multi_domain): https://github.com/criteo-research/pytorch-ada/tree/master/tests/datasets

### LINKED ISSUE #192: [Bug] Pytest Fixutre not Found Error
# 🐛 Bug

When I make the idx_to_class function a pytest fixture, an error occurs saying 'idx' fixture not found. 'idx' is the input parameter to the function and as such I do not know why this error keeps occurring. The code runs properly when I do not make the idx_to_class function a pytest fixture but the pytest fixture would make the code to be more in a pytest style.

## To reproduce
This is the edited code from https://github.com/pykale/pykale/pull/189 which needed changes. The updated version which produced the error is in my forked repository at https://github.com/kennedy12335/pykale/blob/main/tests/loaddata/test_sampler.py. 

code snippet to reproduce the behaviour:

```python
pytest tests/loaddata/test_sampler.py -v
```

** Stack trace/error message **
```
______________________________________________________ ERROR at setup of test_balanced_small_batches _______________________________________________________
file /Users/kennedydike/Documents/GitHub/pykale/tests/loaddata/test_sampler.py, line 24
  def test_balanced_small_batches(idx_to_class):
file /Users/kennedydike/Documents/GitHub/pykale/tests/loaddata/test_sampler.py, line 14
  @pytest.fixture(scope = "module")
  def idx_to_class(idx):
E       fixture 'idx' not found
>       available fixtures: anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, download_path, gait, idx_to_class, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/kennedydike/Documents/GitHub/pykale/tests/loaddata/test_sampler.py:14
______________________________________________________ ERROR at setup of test_balanced_bigger_batches ______________________________________________________
file /Users/kennedydike/Documents/GitHub/pykale/tests/loaddata/test_sampler.py, line 45
  def test_balanced_bigger_batches(idx_to_class):
file /Users/kennedydike/Documents/GitHub/pykale/tests/loaddata/test_sampler.py, line 14
  @pytest.fixture(scope = "module")
  def idx_to_class(idx):
E       fixture 'idx' not found
>       available fixtures: anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, cov, doctest_namespace, download_path, gait, idx_to_class, monkeypatch, no_cover, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/Users/kennedydike/Documents/GitHub/pykale/tests/loaddata/test_sampler.py:14
```

## Expected Behaviour

No error expected and a pass/fail outcome for each test

## Environment
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.2)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.8 (default, Apr 13 2021, 12:59:45)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: macOS-10.15.7-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] numpydoc==1.1.0
[pip3] pytorch-lightning==1.3.8
[pip3] pytorch-memlab==0.2.3
[pip3] torch==1.9.0
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==1.7.2
[pip3] torch-scatter==2.0.7
[pip3] torch-sparse==0.6.10
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.9.0a0+33b2469
[pip3] torchmetrics==0.4.1
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] mkl                       2021.2.0           hecd8cb5_269  
[conda] mkl-service               2.3.0            py38h9ed2024_1  
[conda] mkl_fft                   1.3.0            py38h4a7008c_2  
[conda] mkl_random                1.2.1            py38hb2f4e1b_2  
[conda] numpy                     1.20.1           py38hd6e1bb9_0  
[conda] numpy-base                1.20.1           py38h585ceec_0  
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1  
[conda] pytorch                   1.9.0                   py3.8_0    pytorch
[conda] pytorch-cluster           1.5.9           py38_torch_1.9.0_cpu    rusty1s
[conda] pytorch-geometric         1.7.2           py38_torch_1.9.0_cpu    rusty1s
[conda] pytorch-lightning         1.3.8                    pypi_0    pypi
[conda] pytorch-memlab            0.2.3                    pypi_0    pypi
[conda] pytorch-scatter           2.0.7           py38_torch_1.9.0_cpu    rusty1s
[conda] pytorch-sparse            0.6.10          py38_torch_1.9.0_cpu    rusty1s
[conda] pytorch-spline-conv       1.2.1           py38_torch_1.9.0_cpu    rusty1s
[conda] torch                     1.9.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                      py38    pytorch
[conda] torchmetrics              0.4.1                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.10.0                   pypi_0    pypi

## Additional context
I am attempting to rewrite https://github.com/pykale/pykale/pull/189 in a more pytest style so any suggested changes would be appreciated

### PR DESCRIPTION
**Pull request by kennedy12335**
Fixes #192, #191, #190, and part of #185 

### Description
- Creation of test_sampler.py test file to test sampler.py to improve its coverage and the project's overall coverage. 
- Add help on unittest to pytest conversion and test explorer in vscode

### Status
**Ready**

On the right (delete these after selection):

- Select a reviewer if ready for review. Use the suggested one if unsure. @haipinglu 
- Select at least one appropriate label. Creation of a new test File

### Types of changes

- [x] Non-breaking change (fix or new feature that would not break existing functionality).
- [ ] Breaking change (fix or new feature that would cause existing functionality to change).
- [x] New tests added to cover the changes.
- [ ] In-line docstrings updated.
- [ ] [Source for documentation at `docs`](https://github.com/pykale/pykale/tree/main/docs/source) manually updated for new API.

### CODE REVIEW

**Review by haipinglu — CHANGES_REQUESTED** [review]
- Since this is largely copied from https://github.com/criteo-research/pytorch-ada/blob/master/tests/datasets/test_sampler.py, this source should be referenced here at the top. Refer to 2nd last bullet of [coding style](https://github.com/pykale/pykale/blob/main/.github/CONTRIBUTING.md#coding-style) and examples such as https://github.com/pykale/pykale/blob/main/kale/loaddata/sampler.py or https://github.com/pykale/pykale/blob/main/kale/loaddata/dataset_access.py (see the reference at the top)
- Good to see it worked and has improved the coverage. However, it was not written in the pytest style that we adopted. You may browse through some pytest tests (in pykale and references) to learn, e.g. using fixtures. 
 
@bobturneruk I think this should be rewritten into pytest-style. Am I right? Any suggestions?

**Comment by haipinglu** [comment]
@kennedy12335 Try to describe PR/commit using verbs to indicate actions. See my change to your PR description above.

**Comment by kennedy12335** [comment]
@haipinglu Thank you for the comments. I spent most of today trying to see how I can rewrite the file in pytest a style. However, I do not currently see what I can change. One of the main differences between unittest style and pytest is the assertions which I changed. Could you be a little more specific on how I can make the code more pytest like. I have gone through the documentations and other test files but I am still confused. Perhaps using a few lines of code will help me understand better.

**Comment by haipinglu** [comment]
I suggest you to browse through other pykale tests to observe what's common in the other tests what yours differs here. I've pointed out one such difference, other tests use pytest fixture but you did not use fixture. Instead, you use other ways and the class to define similar things, following the unittest from the source. Also, defining of the class `TestBatchSamplers` is unnecessary. See other tests in pykale, and you should see the differences clearly.

**Review by haipinglu — APPROVED** [review]

**Comment by haipinglu** [comment]
@kennedy12335 Well done! The description at the top should be updated to reflect the new changes (this PR fixes several issues), which I did for your reference (and you should do for similar scenarios in future).

**Pull request merged**
