### PR TITLE
Add notebook "smoke tests" to CI

### LINKED ISSUE #214: [Feature Request] Tests for notebooks
# 🚀 Feature Request

Add basic tests for the tutorial notebooks. 

## Motivation

Changes to dependencies can cause notebooks to fail unexpectedly.

## Pitch

Using GitHub actions, these should:

- Set up an appropriate execution environment
- Convert the notebook to a script
- Run the script
- Report failure if there is an error

**Describe alternatives you've considered**

Regression tests would be very time consuming.

**Are you willing to open a pull request?** Yes

### PR DESCRIPTION
**Pull request by bobturneruk**
Fixes #214 

### Description
Adds action to run PyKale tutorial notebooks as part of the existing CI testing workflow. Running as a separate action would lead to some duplication of the setup yaml, but faster execution.

### Status
**Work in progress**

On the right (delete these after selection):

- Select a reviewer if ready for review. Use the suggested one if unsure.

### Types of changes
- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Comment by bobturneruk** [comment]
I'm having huge problems getting `nbmake` to run locally on Windows 10.

**Comment by alex-treebeard** [comment]
Hi @bobturneruk, sorry to see nbmake isn't working for you. Given we already test on windows, if you can provide any details for repro-ing then I'll get this fixed. ([issue](https://github.com/treebeardtech/nbmake/issues/46))

**Comment by bobturneruk** [comment]
Thanks for getting in touch @alex-treebeard - this is almost certainly a problem with **me** trying to do things in a rush! If I identify something that looks like it could be a genuine issue with `nbmake`, I'll fill in the details.

**Comment by bobturneruk** [comment]
Link to failed action: https://github.com/pykale/pykale/runs/3630198970?check_suite_focus=true

**Comment by alex-treebeard** [comment]
Hi folks, I've just released nbmake 0.8 with a bugfix for notebooks which live next to `__init__.py` files, like yours.

Please try running locally with `pytest --nbmake` once you have installed the new version and let me know how it goes!

**Comment by bobturneruk** [comment]
Fixes the problem @alex-treebeard - thank you so much! Notebooks are failing locally - I need to check the notebooks for problems next.

**Comment by bobturneruk** [comment]
Just had a timeout on Windows 10 last time so I'm going to re-run in case it was a problem with the specific runner https://github.com/pykale/pykale/runs/3661651599?check_suite_focus=true

**Comment by bobturneruk** [comment]
I may need to configure this https://github.com/treebeardtech/nbmake#allow-errors-and-configure-cell-timeouts

**Comment by bobturneruk** [comment]
`examples/bindingdb_deepdta/tutorial.ipynb` runs OK locally on Windows 10. Takes 4min 13s to train on CPU.

**Review by haipinglu — APPROVED** [review]

**Pull request merged**
