### PR TITLE
Retry all tests

### LINKED ISSUE #278: [Feature Request] A second chance in scheduled tests
# 🚀 Feature Request

Give a second chance upon a scheduled test fail.

## Motivation

Recent fails in scheduled tests are all due to a temporary server issue at Zenodo that can be fixed by a simple rerun after a few hours. Why not automate this to reduce the overhead and reduce "false alarms"? Hence the suggestion above.

## Pitch

In the scheduled tests, if failed for the first time, wait for a few (e.g. 5) hours to run it again and raise an issue only if the second run after a few hours fails too.

### PR DESCRIPTION
**Pull request by bobturneruk**
Fixes #278

### Description
Current approach is to retry the tests as part of the workflow prior to formally failing.

### Status
**Work in progress**

If you've been given access to pykale with role Triage or above, on the right (delete these after selection):

- **When** your pull request is **ready** for review, select a reviewer. Use the suggested one if unsure.

### Types of changes
- [x] Non-breaking change (fix or new feature that would not break existing functionality).

### CODE REVIEW

**Comment by haipinglu** [comment]
@bobturneruk Hi Bob, could you please give us a brief status summary and the remaining problems so that we can discuss how to proceed? Multiple failure issues were created recently. Many thanks.

**Comment by bobturneruk** [comment]
https://github.com/pykale/pykale/pull/304 should be merged first.

**Comment by bobturneruk** [comment]
This is where I'm stuck https://github.com/nick-fields/retry/issues/54

**Comment by bobturneruk** [comment]
Fixing this is beyond me. Needs typscript / javascript skills, or it'll be a hack. I'm going to have to find a different action, or try a different approach.

**Comment by haipinglu** [comment]
Shall we change to sending emails instead of creating an issue?

**Comment by haipinglu** [comment]
@bobturneruk As discussed, this could be closed, as well as the related issue.

**Pull request closed without merging**
